# this is the main config for SpyderFly
# anything you change will be wiped in an update; subject to change
# when updating from a version to a version that requires this file to be rewritten, you will be prompted during the update and will create a backup for you before removing it and updating with the new one


# upstream config:

listen 2026;
root /etc/spyderfly/index/;



include /etc/spyderfly/enabled-sites/*.conf;