[DEFAULT]
debian-branch = debian/latest
upstream-branch = upstream
upstream-tag = upstream/%(version)s
pristine-tar = True
sign-tags = True
upstream-signatures = on
dist = DEP14

[import-orig]
merge-mode = replace

[pull]
track-missing = True
