#!/bin/sh
set -e

MAIN_DIR="/etc/spyderfly"
SITES_DIR="/etc/spyderfly/enabled-sites"
INDEX_DIR="/etc/spyderfly/index"
CONF_DIR="/etc/spyderfly/config"
DIS_SITE="/etc/spyderfly/disabled-sites"
LOG_DIR="/var/spyderfly"
IND_HTM="https://repo.sizablesplash.com/spyderfly/shell-script/working.html"
  # change per version
CURR_VER="https://repo.sizablesplash.com/spyderfly/releases/beta_1.0/beta_1.0"
OUTPUT="/usr/bin/spyderfly"
DEF_CONF="/etc/spyderfly/enabled-sites/default.conf"


echo "Welcome to the SpyderFly web server beta 1.0! Thank you for choosing SpyderFly"

echo "Creating directories..."
mkdir -p "$MAIN_DIR" "$INDEX_DIR" "$SITES_DIR" "$CONF_DIR" "$DIS_SITE" "$LOG_DIR"

if [ -f "$OUTPUT" ]; then
    rm -f "$OUTPUT"
fi

echo "Installing binary..."
curl -sSL "$CURR_VER" -o "$OUTPUT"
chmod +x "$OUTPUT"

if [ ! -f "$INDEX_DIR/index.html" ]; then
  curl -sSL "$IND_HTM" -o "$INDEX_DIR/index.html"
fi

if [ ! -f "$DEF_CONF" ]; then
  mkdir -p "$(dirname "$DEF_CONF")"
  cat << 'EOF' > "$DEF_CONF"
    # Welcome to the SpyderFly web server! Read docs at https://spyderfly.sizablesplash.com
    # This is a work in progress and some things might not work
    # DO NOT DELETE THIS FILE!!!!!!!

    # SpyderFly Server Configuration
    listen 8046;
    server_name localhost;
    root /etc/spyderfly/index/;
  EOF
fi
echo "SpyderFly installed! Thank you for choosing SpyderFly"