#!/bin/sh
set -e

MAIN_DIR="/etc/spyderfly"
SITES_DIR="/etc/spyderfly/sites"
INDEX_DIR="/etc/spyderfly/index"
CONF_DIR="/etc/spyderfly/config"
IND_HTM="https://repo.sizablesplash.com/spyderfly/shell-script/working.html"
  # change per version
CURR_VER="https://repo.sizablesplash.com/spyderfly/releases/beta_1.0/beta_1.0"
  # change per here too
OUTPUT="/usr/bin/spyderfly"

echo "Welcome to the SpyderFly web server beta 1.0! Thank you for choosing SpyderFly"

echo "Creating directories..."
mkdir -p "$MAIN_DIR" "$INDEX_DIR" "$SITES_DIR" "$CONF_DIR"

if [ -f "$OUTPUT" ]; then
    rm -f "$OUTPUT"
fi

echo "Installing binary..."
curl -sSL "$CURR_VER" -o "$OUTPUT"
chmod +x "$OUTPUT"

if [ ! -f "$INDEX_DIR/index.html" ]; then
  curl -sSL "$IND_HTM" -o "$INDEX_DIR/index.html"
fi

echo "SpyderFly installed! Thank you for choosing SpyderFly"