#!/bin/sh
set -e

MAIN_DIR="/etc/spyderfly"
SITES_DIR="/etc/spyderfly/enabled-sites"
INDEX_DIR="/etc/spyderfly/index"
CONF_DIR="/etc/spyderfly/config"
DIS_SITE="/etc/spyderfly/disabled-sites"
LOG_DIR="/var/spyderfly"
IND_HTM="https://repo.sizablesplash.com/spyderfly/shell-script/working.html"
  # change per version
CODE_ZIP="https://repo.sizablesplash.com/spyderfly/releases/v1.0/v1.0.zip"
  # change per version
CODE_OUT="/etc/spyderfly/source-code.zip"
CODE_DIR="/etc/spyderfly/code"
CURR_VER="https://repo.sizablesplash.com/spyderfly/releases/v1.0/v1.0"  # this is for the service
MANG_SF="https://repo.sizablesplash.com/spyderfly/releases/v1.0/manager"  # not in the shell script yet nor code ready
OUTPUT="/usr/bin/spyderfly"  # do this for the managing code
SRVC_OUT="/etc/spyderfly/spyderfly_service"
DEF_CONF="/etc/spyderfly/enabled-sites/default.conf"
MAIN_CONF="/etc/spyderfly/spyderfly.conf"
SRVCE="/etc/systemd/system/spyderfly.service"


echo "Welcome to the SpyderFly web server beta 1.0! Thank you for choosing SpyderFly"

echo "Creating directories..."
mkdir -p "$MAIN_DIR" "$INDEX_DIR" "$SITES_DIR" "$CONF_DIR" "$DIS_SITE" "$LOG_DIR"

if [ -f "$OUTPUT" ]; then
    rm -f "$OUTPUT"
fi

echo "Installing service..."
curl -sSL "$CURR_VER" -o "$SRVC_OUT"  # changed to service
chmod +x "$SRVC_OUT"

echo "installing binary..."  # manager
curl -sSL "$MANG_SF" -o "$OUTPUT"
chmod +x "$OUTPUT"

#echo "Downloading source code..."
#curl -sSL "$CODE_ZIP" -o "$CODE_OUT"
#unzip -o "$CODE_OUT" -d "$CODE_DIR"

if [ ! -f "$INDEX_DIR/index.html" ]; then
  curl -sSL "$IND_HTM" -o "$INDEX_DIR/index.html"
fi

if [ ! -f "$DEF_CONF" ]; then
  mkdir -p "$(dirname "$DEF_CONF")"
  cat << 'EOF' > "$DEF_CONF"
  # Welcome to the SpyderFly web server! Read docs at https://spyderfly.sizablesplash.com
  # This is a work in progress and some things might not work
  # DO NOT DELETE THIS FILE!!!!!!!

  # SpyderFly Server Configuration
  listen 8046;
  server_name localhost;
  root /etc/spyderfly/index/;
EOF
fi

mkdir -p "$(dirname "$MAIN_CONF")"
cat << 'EOF' > "$MAIN_CONF"
# this is the main config for SpyderFly
# anything you change will be wiped in an update

include /etc/spyderfly/enabled-sites/*.conf
EOF

mkdir -p "$(dirname "$SRVCE")"
cat << 'EOF' > "$SRVCE"
[Unit]
Description=SpyderFly Web Server
After=network.target

[Service]
Type=simple
ExecStart=/etc/spyderfly/spyderfly_service
Restart=always

[Install]
WantedBy=multi-user.target
EOF

echo "SpyderFly installed! Thank you for choosing SpyderFly"