  # Welcome to the SpyderFly web server! Read docs at https://spyderfly.sizablesplash.com
  # This is a work in progress and some things might not work
  # DO NOT DELETE THIS FILE!!!!!!!

  # SpyderFly Server Configuration
  listen 8046;
  server_name localhost;
  root /etc/spyderfly/index/;

#note to self, might change this